namespace EasyCPDLC.VNS430
{
    internal enum Vns430Command : byte
    {
        None = 0,
        LargeRightDecrease = 1,
        LargeRightIncrease = 2,
        SmallRightDecrease = 3,
        SmallRightIncrease = 4,
        CursorPush = 5,
        Enter = 6,
        Clear = 7,
        Menu = 8,
        Message = 9,
        FlightPlan = 10,
        Procedure = 11,
        DirectTo = 12,
        Obs = 13,
        Cdi = 14,
        RangeIn = 15,
        RangeOut = 16,
        Nearest = 17,
        Power = 18,
        DcduLeftLsk1 = 19,
        DcduLeftLsk2 = 20,
        DcduLeftLsk3 = 21,
        DcduLeftLsk4 = 22,
        DcduLeftLsk5 = 23,
        DcduLeftLsk6 = 24,
        DcduRightLsk1 = 25,
        DcduRightLsk2 = 26,
        DcduRightLsk3 = 27,
        DcduRightLsk4 = 28,
        DcduRightLsk5 = 29,
        DcduRightLsk6 = 30,
        DcduConnect = 31,
        DcduAoc = 32,
        DcduAtc = 33,
        DcduSettings = 34,
        DcduReloadFlightPlan = 35,
        DcduPrint = 36,
        DcduReprint = 37,
        DcduHide = 38
    }
}
