namespace EasyCPDLC.VNS430
{
    internal enum Vns430Command : byte
    {
        None = 0,
        LargeRightDecrease = 1,
        LargeRightIncrease = 2,
        SmallRightDecrease = 3,
        SmallRightIncrease = 4,
        CursorPush = 5,
        Enter = 6,
        Clear = 7,
        Menu = 8,
        Message = 9,
        FlightPlan = 10,
        Procedure = 11,
        DirectTo = 12,
        Obs = 13,
        Cdi = 14,
        RangeIn = 15,
        RangeOut = 16,
        Nearest = 17,
        Power = 18,
        DcduLeftLsk1 = 19,
        DcduLeftLsk2 = 20,
        DcduLeftLsk3 = 21,
        DcduLeftLsk4 = 22,
        DcduLeftLsk5 = 23,
        DcduLeftLsk6 = 24,
        DcduRightLsk1 = 25,
        DcduRightLsk2 = 26,
        DcduRightLsk3 = 27,
        DcduRightLsk4 = 28,
        DcduRightLsk5 = 29,
        DcduRightLsk6 = 30,
        DcduConnect = 31,
        DcduAoc = 32,
        DcduAtc = 33,
        DcduSettings = 34,
        DcduReloadFlightPlan = 35,
        DcduPrint = 36,
        DcduReprint = 37,
        DcduHide = 38,

        // Boeing CDU (PFP/FMC) keypad, used by the LSK-only CDU display mode. The alpha and
        // digit keys occupy contiguous ranges so the app can map a command straight to a
        // character; the bridge exposes one EASYCPDLC_CDU_* L-var per key.
        CduAlphaA = 39,  // A..Z occupy 39..64
        CduAlphaZ = 64,
        CduDigit0 = 65,  // 0..9 occupy 65..74
        CduDigit9 = 74,
        CduSpace = 75,
        CduDot = 76,
        CduSlash = 77,
        CduPlusMinus = 78,
        CduClear = 79,
        CduDelete = 80,

        CduInitRef = 81,
        CduRoute = 82,
        CduDepArr = 83,
        CduAtcPage = 84,
        CduVnav = 85,
        CduFix = 86,
        CduLegs = 87,
        CduHold = 88,
        CduFmcComm = 89,
        CduProg = 90,
        CduExec = 91,
        CduMenu = 92,
        CduNavRad = 93,
        CduPrevPage = 94,
        CduNextPage = 95,
        CduBrightnessUp = 96,
        CduBrightnessDown = 97
    }
}
